# https://raw.githubusercontent.com/mojolicious/mojo/main/.github/workflows/linux.yml
name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
#         - '5.14' # Mojolyst says five fouteen is fine, but mojo doesn't install there on github workers
          - '5.32'
          - '5.16'
#          - '5.18'
#          - '5.20'
#          - '5.22'
#          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
      - name: Run tests
        run: prove --verbose -l t
        env:
          TEST_POD: 1
          TEST_EV: 1
